import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#faf9fd',
        surface: '#faf9fd',
        'surface-dim': '#dad9dd',
        'surface-bright': '#faf9fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f7',
        'surface-container': '#efedf1',
        'surface-container-high': '#e9e7eb',
        'surface-container-highest': '#e3e2e6',
        'surface-variant': '#e3e2e6',
        'on-background': '#1a1b1e',
        'on-surface': '#1a1b1e',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        outline: '#74777f',
        'outline-variant': '#c4c6cf',
        primary: '#002046',
        'on-primary': '#ffffff',
        'primary-container': '#1b365d',
        'on-primary-container': '#87a0cd',
        'inverse-primary': '#aec7f7',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aec7f7',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#2e476f',
        secondary: '#466557',
        'on-secondary': '#ffffff',
        'secondary-container': '#c5e7d6',
        'on-secondary-container': '#2f4d40',
        'secondary-fixed': '#c8ead9',
        'secondary-fixed-dim': '#adcebe',
        'on-secondary-fixed': '#012016',
        'on-secondary-fixed-variant': '#2f4d40',
        tertiary: '#20211e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#363633',
        'on-tertiary-container': '#a09f9a',
        'tertiary-fixed': '#e4e2dd',
        'tertiary-fixed-dim': '#c8c6c2',
        'on-tertiary-fixed': '#1b1c19',
        'on-tertiary-fixed-variant': '#474744',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        linen: '#f9f7f2',
        sage: '#7a9a8b',
      },
      fontFamily: {
        sans: ['Lexend', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        display: ['3rem', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '0' }],
        h1: ['2rem', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '0' }],
        h2: ['1.5rem', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0' }],
        h3: ['1.25rem', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400', letterSpacing: '0' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400', letterSpacing: '0' }],
        'label-caps': ['0.875rem', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.05em' }],
        button: ['1rem', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0' }],
      },
      spacing: {
        unit: '8px',
        'container-max': '1280px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-gap': '80px',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(27, 54, 93, 0.1)',
        card: '0 4px 20px rgba(27, 54, 93, 0.08)',
        overlay: '0 20px 45px rgba(27, 54, 93, 0.16)',
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [forms],
}